### ISSUE TITLE
TeleboyNG not login in anymore

### ISSUE THREAD

**Issue by bruno-briner** [fillab/teleboyNG_BIN#5]
Teleboy might have changed again the login procedure. Below the kodi.log part 

20:34:32 6240.151367 T:1344271264  NOTICE: ### fetchHttp(GET): https://www.teleboy.ch/login
20:34:33 6240.417969 T:1344271264  NOTICE: ### fetchHttp(GET): https://www.teleboy.ch/live
20:34:33 6240.713379 T:1344271264  NOTICE: ### logging in...
20:34:33 6240.716309 T:1344271264  NOTICE: ### fetchHttp(POST): https://www.teleboy.ch/login_check
20:34:33 6240.716797 T:1344271264  NOTICE: ### args-keys: ['login', 'password', 'keep_login']
20:34:34 6241.731934 T:1344271264  NOTICE: ### login failure
20:34:34 6241.737793 T:1344271264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'latin-1' codec can't encode character u'\u2013' in position 4503: ordinal not in range(256)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.teleboyNG/teleboy.py", line 282, in <module>
                                                if not ensure_login():
                                              File "/storage/.kodi/addons/plugin.video.teleboyNG/teleboy.py", line 97, in ensure_login
                                                log( reply)
                                              File "/storage/.kodi/addons/script.module.mindmadetools/lib/mindmade.py", line 28, in log
                                                msg = msg.encode( "latin-1")
                                            UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2013' in position 4503: ordinal not in range(256)
                                            -->End of Python script error report<--
20:34:34 6242.076172 T:1962438656   ERROR: GetDirectory - Error getting plugin://plugin.video.teleboyNG/?mode=live_fav
20:34:34 6242.080078 T:1962438656   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.teleboyNG/?mode=live_fav) failed

**Comment by benbois** [comment]
to avoid the latin-1 error, you have to modify the line in the file /storage/.kodi/addons/script.module.mindmadetools/lib/mindmade.py : 
from >
 `msg = msg.encode( "latin-1")`
to >
 `msg = msg.encode( "utf-8")`

But it is not a fix for the teleboy login problem.
I get the same one too.

**Comment by benbois** [comment]
Okay, I have a fix.
Open the file addons/plugin.video.teleboyNG/teleboy.py and modify the followed lines:
```
#    if updateSessionCookie( cookies) and updateUserID( reply):
    if updateSessionCookie( cookies):
        cookies.save( ignore_discard=True)
        url = TB_URL + "/live"
        reply = fetchHttp( url )
        if updateUserID( reply):
            log( "login ok")
            return True
```
In fact, the user_id is now located only in the page https://www.teleboy.ch/live and not any more in the page  https://www.teleboy.ch/login_check

**Comment by greystashh** [comment]
Would it be possible for you to upload your modified teleboy.py?

**Comment by benbois** [comment]
sure, here you are:
- https://github.com/benbois/teleboyNG_BIN/blob/master/plugin.video.teleboyNG/teleboy.py

**Comment by greystashh** [comment]
Thanks

**Comment by bruno-briner** [comment]
Thank you! You could also make a PR to fillab!
